/*

    Copyright 2013, 2014, 2015, 2016, 2017, 2018  joshua.tee@gmail.com

    This file is part of wX.

    wX is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    wX is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with wX.  If not, see <http://www.gnu.org/licenses/>.

 */

package joshuatee.wx.settings

import android.content.Context
import android.preference.PreferenceManager

object UtilityPref {

    fun prefInitNWSLoc(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("NWS_LOCATION_JSJ", null)
        if (value == null) {
            editor.putString("NWS_LOCATION_AFC", "AK, Anchorage")
            editor.putString("NWS_LOCATION_AFG", "AK, Fairbanks")
            editor.putString("NWS_LOCATION_AJK", "AK, Juneau")
            editor.putString("NWS_LOCATION_ANC", "AK, Anchorage")
            editor.putString("NWS_LOCATION_BMX", "AL, Birmingham")
            editor.putString("NWS_LOCATION_HUN", "AL, Huntsville")
            editor.putString("NWS_LOCATION_MOB", "AL, Mobile")
            editor.putString("NWS_LOCATION_LZK", "AR, Little Rock")
            editor.putString("NWS_LOCATION_FGZ", "AZ, Flagstaff")
            editor.putString("NWS_LOCATION_PSR", "AZ, Phoenix")
            editor.putString("NWS_LOCATION_TWC", "AZ, Tucson")
            editor.putString("NWS_LOCATION_EKA", "CA, Eureka")
            editor.putString("NWS_LOCATION_HNX", "CA, Hanford")
            editor.putString("NWS_LOCATION_LOX", "CA, Los Angeles")
            editor.putString("NWS_LOCATION_MTR", "CA, San Francisco")
            editor.putString("NWS_LOCATION_SGX", "CA, San Diego")
            editor.putString("NWS_LOCATION_STO", "CA, Sacramento")
            editor.putString("NWS_LOCATION_BOU", "CO, Denver/Boulder")
            editor.putString("NWS_LOCATION_GJT", "CO, Grand Junction")
            editor.putString("NWS_LOCATION_PUB", "CO, Pueblo")
            editor.putString("NWS_LOCATION_JAX", "FL, Jacksonville")
            editor.putString("NWS_LOCATION_KEY", "FL, Key West")
            editor.putString("NWS_LOCATION_MFL", "FL, Miami")
            editor.putString("NWS_LOCATION_MLB", "FL, Melbourne")
            editor.putString("NWS_LOCATION_TAE", "FL, Tallahassee")
            editor.putString("NWS_LOCATION_TBW", "FL, Tampa Bay")
            editor.putString("NWS_LOCATION_FFC", "GA, Atlanta")
            editor.putString("NWS_LOCATION_GUM", "GU, Guam")
            editor.putString("NWS_LOCATION_HFO", "HI, Honolulu")
            editor.putString("NWS_LOCATION_DMX", "IA, Des Moines")
            editor.putString("NWS_LOCATION_DVN", "IA, Quad Cities")
            editor.putString("NWS_LOCATION_BOI", "ID, Boise")
            editor.putString("NWS_LOCATION_PIH", "ID, Pocatello")
            editor.putString("NWS_LOCATION_ILX", "IL, Lincoln")
            editor.putString("NWS_LOCATION_LOT", "IL, Chicago")
            editor.putString("NWS_LOCATION_IND", "IN, Indianapolis")
            editor.putString("NWS_LOCATION_IWX", "IN, Nrn. Indiana")
            editor.putString("NWS_LOCATION_DDC", "KS, Dodge City")
            editor.putString("NWS_LOCATION_GLD", "KS, Goodland")
            editor.putString("NWS_LOCATION_ICT", "KS, Wichita")
            editor.putString("NWS_LOCATION_TOP", "KS, Topeka")
            editor.putString("NWS_LOCATION_JKL", "KY, Jackson")
            editor.putString("NWS_LOCATION_LMK", "KY, Louisville")
            editor.putString("NWS_LOCATION_PAH", "KY, Paducah")
            editor.putString("NWS_LOCATION_LCH", "LA, Lake Charles")
            editor.putString("NWS_LOCATION_LIX", "LA, New Orleans")
            editor.putString("NWS_LOCATION_SHV", "LA, Shreveport")
            editor.putString("NWS_LOCATION_BOX", "MA, Boston")
            editor.putString("NWS_LOCATION_CAR", "ME, Caribou")
            editor.putString("NWS_LOCATION_GYX", "ME, Gray")
            editor.putString("NWS_LOCATION_APX", "MI, Gaylord")
            editor.putString("NWS_LOCATION_DTX", "MI, Detroit")
            editor.putString("NWS_LOCATION_GRR", "MI, Grand Rapids")
            editor.putString("NWS_LOCATION_MQT", "MI, Marquette")
            editor.putString("NWS_LOCATION_DLH", "MN, Duluth")
            editor.putString("NWS_LOCATION_MPX", "MN, Twin Cities")
            editor.putString("NWS_LOCATION_EAX", "MO, Kansas City")
            editor.putString("NWS_LOCATION_LSX", "MO, St. Louis")
            editor.putString("NWS_LOCATION_SGF", "MO, Springfield")
            editor.putString("NWS_LOCATION_JAN", "MS, Jackson")
            editor.putString("NWS_LOCATION_BYZ", "MT, Billings")
            editor.putString("NWS_LOCATION_GGW", "MT, Glasgow")
            editor.putString("NWS_LOCATION_MSO", "MT, Missoula")
            editor.putString("NWS_LOCATION_TFX", "MT, Great Falls")
            editor.putString("NWS_LOCATION_ILM", "NC, Wilmington")
            editor.putString("NWS_LOCATION_MHX", "NC, Morehead City")
            editor.putString("NWS_LOCATION_RAH", "NC, Raleigh")
            editor.putString("NWS_LOCATION_BIS", "ND, Bismarck")
            editor.putString("NWS_LOCATION_FGF", "ND, Grand Forks")
            editor.putString("NWS_LOCATION_GID", "NE, Hastings")
            editor.putString("NWS_LOCATION_LBF", "NE, North Platte")
            editor.putString("NWS_LOCATION_OAX", "NE, Omaha")
            editor.putString("NWS_LOCATION_PHI", "NJ, Mount Holly")
            editor.putString("NWS_LOCATION_ABQ", "NM, Albuquerque")
            editor.putString("NWS_LOCATION_LKN", "NV, Elko")
            editor.putString("NWS_LOCATION_REV", "NV, Reno")
            editor.putString("NWS_LOCATION_VEF", "NV, Las Vegas")
            editor.putString("NWS_LOCATION_ALY", "NY, Albany")
            editor.putString("NWS_LOCATION_BGM", "NY, Binghamton")
            editor.putString("NWS_LOCATION_BUF", "NY, Buffalo")
            editor.putString("NWS_LOCATION_OKX", "NY, New York City")
            editor.putString("NWS_LOCATION_CLE", "OH, Cleveland")
            editor.putString("NWS_LOCATION_ILN", "OH, Wilmington")
            editor.putString("NWS_LOCATION_OUN", "OK, Norman")
            editor.putString("NWS_LOCATION_TSA", "OK, Tulsa")
            editor.putString("NWS_LOCATION_MFR", "OR, Medford")
            editor.putString("NWS_LOCATION_PDT", "OR, Pendleton")
            editor.putString("NWS_LOCATION_PQR", "OR, Portland")
            editor.putString("NWS_LOCATION_CTP", "PA, State College")
            editor.putString("NWS_LOCATION_PBZ", "PA, Pittsburgh")
            editor.putString("NWS_LOCATION_SJU", "PR, San Juan")
            editor.putString("NWS_LOCATION_JSJ", "PR, San Juan")
            editor.putString("NWS_LOCATION_CAE", "SC, Columbia")
            editor.putString("NWS_LOCATION_CHS", "SC, Charleston")
            editor.putString("NWS_LOCATION_GSP", "SC, Greer")
            editor.putString("NWS_LOCATION_ABR", "SD, Aberdeen")
            editor.putString("NWS_LOCATION_FSD", "SD, Sioux Falls")
            editor.putString("NWS_LOCATION_UNR", "SD, Rapid City")
            editor.putString("NWS_LOCATION_MEG", "TN, Memphis")
            editor.putString("NWS_LOCATION_MRX", "TN, Morristown")
            editor.putString("NWS_LOCATION_OHX", "TN, Nashville")
            editor.putString("NWS_LOCATION_AMA", "TX, Amarillo")
            editor.putString("NWS_LOCATION_BRO", "TX, Brownsville")
            editor.putString("NWS_LOCATION_CRP", "TX, Corpus Christi")
            editor.putString("NWS_LOCATION_EPZ", "TX, El Paso")
            editor.putString("NWS_LOCATION_EWX", "TX, Austin")
            editor.putString("NWS_LOCATION_FWD", "TX, Dallas")
            editor.putString("NWS_LOCATION_HGX", "TX, Houston")
            editor.putString("NWS_LOCATION_LUB", "TX, Lubbock")
            editor.putString("NWS_LOCATION_MAF", "TX, Midland")
            editor.putString("NWS_LOCATION_SJT", "TX, San Angelo")
            editor.putString("NWS_LOCATION_SLC", "UT, Salt Lake City")
            editor.putString("NWS_LOCATION_AKQ", "VA, Wakefield")
            editor.putString("NWS_LOCATION_LWX", "VA, Sterling")
            editor.putString("NWS_LOCATION_RNK", "VA, Blacksburg")
            editor.putString("NWS_LOCATION_BTV", "VT, Burlington")
            editor.putString("NWS_LOCATION_OTX", "WA, Spokane")
            editor.putString("NWS_LOCATION_SEW", "WA, Seattle")
            editor.putString("NWS_LOCATION_ARX", "WI, La Crosse")
            editor.putString("NWS_LOCATION_GRB", "WI, Green Bay")
            editor.putString("NWS_LOCATION_MKX", "WI, Milwaukee")
            editor.putString("NWS_LOCATION_RLX", "WV, Charleston")
            editor.putString("NWS_LOCATION_CYS", "WY, Cheyenne")
            editor.putString("NWS_LOCATION_RIW", "WY, Riverton")
            editor.apply()
        }
    }

    fun prefInitBig(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("NWS_RID_JSJ", null)
        if (value == null) {
            editor.putString("NWS_RID_ABQ", "ABX")
            editor.putString("NWS_RID_ABR", "ABR")
            editor.putString("NWS_RID_AFC", "AHG")
            editor.putString("NWS_RID_AFG", "APD")
            editor.putString("NWS_RID_AJK", "ACG")
            editor.putString("NWS_RID_AKQ", "AKQ")
            editor.putString("NWS_RID_ALY", "ENX")
            editor.putString("NWS_RID_AMA", "AMA")
            editor.putString("NWS_RID_ANC", "ANC")
            editor.putString("NWS_RID_APX", "APX")
            editor.putString("NWS_RID_ARX", "ARX")
            editor.putString("NWS_RID_BGM", "BGM")
            editor.putString("NWS_RID_BIS", "BIS")
            editor.putString("NWS_RID_BMX", "BMX")
            editor.putString("NWS_RID_BOI", "CBX")
            editor.putString("NWS_RID_BOU", "FTG")
            editor.putString("NWS_RID_BOX", "BOX")
            editor.putString("NWS_RID_BRO", "BRO")
            editor.putString("NWS_RID_BTV", "CXX")
            editor.putString("NWS_RID_BUF", "BUF")
            editor.putString("NWS_RID_BYZ", "BLX")
            editor.putString("NWS_RID_CAE", "CAE")
            editor.putString("NWS_RID_CAR", "CBW")
            editor.putString("NWS_RID_CHS", "CLX")
            editor.putString("NWS_RID_CLE", "CLE")
            editor.putString("NWS_RID_CRP", "CRP")
            editor.putString("NWS_RID_CTP", "CCX")
            editor.putString("NWS_RID_CYS", "CYS")
            editor.putString("NWS_RID_DDC", "DDC")
            editor.putString("NWS_RID_DLH", "DLH")
            editor.putString("NWS_RID_DMX", "DMX")
            editor.putString("NWS_RID_DTX", "DTX")
            editor.putString("NWS_RID_DVN", "DVN")
            editor.putString("NWS_RID_EAX", "EAX")
            editor.putString("NWS_RID_EKA", "BHX")
            editor.putString("NWS_RID_EPZ", "EPZ")
            editor.putString("NWS_RID_EWX", "EWX")
            editor.putString("NWS_RID_FFC", "FFC")
            editor.putString("NWS_RID_FGF", "MVX")
            editor.putString("NWS_RID_FGZ", "FSX")
            editor.putString("NWS_RID_FSD", "FSD")
            editor.putString("NWS_RID_FWD", "FWS")
            editor.putString("NWS_RID_GGW", "GGW")
            editor.putString("NWS_RID_GID", "UEX")
            editor.putString("NWS_RID_GJT", "GJX")
            editor.putString("NWS_RID_GLD", "GLD")
            editor.putString("NWS_RID_GRB", "GRB")
            editor.putString("NWS_RID_GRR", "GRR")
            editor.putString("NWS_RID_GSP", "GSP")
            editor.putString("NWS_RID_GUM", "GUA")
            editor.putString("NWS_RID_GYX", "GYX")
            editor.putString("NWS_RID_HFO", "HMO")
            editor.putString("NWS_RID_HGX", "HGX")
            editor.putString("NWS_RID_HNX", "HNX")
            editor.putString("NWS_RID_HUN", "HTX")
            editor.putString("NWS_RID_ICT", "ICT")
            editor.putString("NWS_RID_ILM", "LTX")
            editor.putString("NWS_RID_ILN", "ILN")
            editor.putString("NWS_RID_ILX", "ILX")
            editor.putString("NWS_RID_IND", "IND")
            editor.putString("NWS_RID_IWX", "IWX")
            editor.putString("NWS_RID_JAN", "DGX")
            editor.putString("NWS_RID_JAX", "JAX")
            editor.putString("NWS_RID_JKL", "JKL")
            editor.putString("NWS_RID_KEY", "BYX")
            editor.putString("NWS_RID_LBF", "LNX")
            editor.putString("NWS_RID_LCH", "LCH")
            editor.putString("NWS_RID_LIX", "LIX")
            editor.putString("NWS_RID_LKN", "LRX")
            editor.putString("NWS_RID_LMK", "LVX")
            editor.putString("NWS_RID_LOT", "LOT")
            editor.putString("NWS_RID_LOX", "VTX")
            editor.putString("NWS_RID_LSX", "LSX")
            editor.putString("NWS_RID_LUB", "LBB")
            editor.putString("NWS_RID_LWX", "LWX")
            editor.putString("NWS_RID_LZK", "LZK")
            editor.putString("NWS_RID_MAF", "MAF")
            editor.putString("NWS_RID_MEG", "NQA")
            editor.putString("NWS_RID_MFL", "AMX")
            editor.putString("NWS_RID_MFR", "MAX")
            editor.putString("NWS_RID_MHX", "MHX")
            editor.putString("NWS_RID_MKX", "MKX")
            editor.putString("NWS_RID_MLB", "MLB")
            editor.putString("NWS_RID_MOB", "MOB")
            editor.putString("NWS_RID_MPX", "MPX")
            editor.putString("NWS_RID_MQT", "MQT")
            editor.putString("NWS_RID_MRX", "MRX")
            editor.putString("NWS_RID_MSO", "MSX")
            editor.putString("NWS_RID_MTR", "MUX")
            editor.putString("NWS_RID_OAX", "OAX")
            editor.putString("NWS_RID_OHX", "OHX")
            editor.putString("NWS_RID_OKX", "OKX")
            editor.putString("NWS_RID_OTX", "OTX")
            editor.putString("NWS_RID_OUN", "TLX")
            editor.putString("NWS_RID_PAH", "PAH")
            editor.putString("NWS_RID_PBZ", "PBZ")
            editor.putString("NWS_RID_PDT", "PDT")
            editor.putString("NWS_RID_PHI", "DIX")
            editor.putString("NWS_RID_PIH", "SFX")
            editor.putString("NWS_RID_PQR", "RTX")
            editor.putString("NWS_RID_PSR", "IWA")
            editor.putString("NWS_RID_PUB", "PUX")
            editor.putString("NWS_RID_RAH", "RAX")
            editor.putString("NWS_RID_REV", "RGX")
            editor.putString("NWS_RID_RIW", "RIW")
            editor.putString("NWS_RID_RLX", "RLX")
            editor.putString("NWS_RID_RNK", "FCX")
            editor.putString("NWS_RID_SEW", "ATX")
            editor.putString("NWS_RID_SGF", "SGF")
            editor.putString("NWS_RID_SGX", "NKX")
            editor.putString("NWS_RID_SHV", "SHV")
            editor.putString("NWS_RID_SJT", "SJT")
            editor.putString("NWS_RID_SJU", "JUA")
            editor.putString("NWS_RID_JSJ", "JUA")
            editor.putString("NWS_RID_SLC", "MTX")
            editor.putString("NWS_RID_STO", "DAX")
            editor.putString("NWS_RID_TAE", "TLH")
            editor.putString("NWS_RID_TBW", "TBW")
            editor.putString("NWS_RID_TFX", "TFX")
            editor.putString("NWS_RID_TOP", "TWX")
            editor.putString("NWS_RID_TSA", "INX")
            editor.putString("NWS_RID_TWC", "EMX")
            editor.putString("NWS_RID_UNR", "UDX")
            editor.putString("NWS_RID_VEF", "ESX")
            editor.putString("STATE_TW_ID_AL", "410946082747596800")
            editor.putString("STATE_TW_ID_AK", "410946674685509632")
            editor.putString("STATE_TW_ID_AZ", "410946812913008640")
            editor.putString("STATE_TW_ID_AR", "410946983583428608")
            editor.putString("STATE_TW_ID_CA", "410947133554966530")
            editor.putString("STATE_TW_ID_CO", "410947263117004802")
            editor.putString("STATE_TW_ID_CT", "410947401004773376")
            editor.putString("STATE_TW_ID_DE", "410947531611185153")
            editor.putString("STATE_TW_ID_FL", "410947683067498496")
            editor.putString("STATE_TW_ID_GA", "410947813162225664")
            editor.putString("STATE_TW_ID_HI", "410947943412137984")
            editor.putString("STATE_TW_ID_ID", "410948063646076928")
            editor.putString("STATE_TW_ID_IL", "410948185452838912")
            editor.putString("STATE_TW_ID_IN", "410948324535988224")
            editor.putString("STATE_TW_ID_IA", "410948449949847553")
            editor.putString("STATE_TW_ID_KS", "410948583387459584")
            editor.putString("STATE_TW_ID_KY", "410948713557663746")
            editor.putString("STATE_TW_ID_LA", "410948840821239810")
            editor.putString("STATE_TW_ID_ME", "410948966411300865")
            editor.putString("STATE_TW_ID_MD", "410949089140813824")
            editor.putString("STATE_TW_ID_MA", "410949206115762176")
            editor.putString("STATE_TW_ID_MI", "406095836829855744")
            editor.putString("STATE_TW_ID_MN", "410949323623395329")
            editor.putString("STATE_TW_ID_MS", "410949449737703424")
            editor.putString("STATE_TW_ID_MO", "410949571464806400")
            editor.putString("STATE_TW_ID_MT", "410949718403842048")
            editor.putString("STATE_TW_ID_NE", "410949838730035200")
            editor.putString("STATE_TW_ID_NV", "410949972331212800")
            editor.putString("STATE_TW_ID_NH", "410950086571474944")
            editor.putString("STATE_TW_ID_NJ", "410950242838646785")
            editor.putString("STATE_TW_ID_NM", "410950366134419457")
            editor.putString("STATE_TW_ID_NY", "410950487198793728")
            editor.putString("STATE_TW_ID_NC", "410950603993411584")
            editor.putString("STATE_TW_ID_ND", "410950714639138816")
            editor.putString("STATE_TW_ID_OH", "410950826153099264")
            editor.putString("STATE_TW_ID_OK", "410950956541415424")
            editor.putString("STATE_TW_ID_OR", "410951075554803712")
            editor.putString("STATE_TW_ID_PA", "410951192261316608")
            editor.putString("STATE_TW_ID_RI", "410951324608385026")
            editor.putString("STATE_TW_ID_SC", "410951462919745537")
            editor.putString("STATE_TW_ID_SD", "410951576107237376")
            editor.putString("STATE_TW_ID_TN", "410951698291507202")
            editor.putString("STATE_TW_ID_TX", "410951810052939777")
            editor.putString("STATE_TW_ID_UT", "410951924230279168")
            editor.putString("STATE_TW_ID_VT", "410952117885472768")
            editor.putString("STATE_TW_ID_VA", "410952264191205376")
            editor.putString("STATE_TW_ID_WA", "410952480776667136")
            editor.putString("STATE_TW_ID_WV", "410952602067550208")
            editor.putString("STATE_TW_ID_WI", "410952736549502977")
            editor.putString("STATE_TW_ID_WY", "410952874370162688")
            editor.apply()
        }
    }

    fun prefInitTwitterCA(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        var value = preferences.getString("STATE_TW_ID_bcstorm", null)
        if (value == null) {
            editor.putString("STATE_TW_ID_bcstorm", "489578049524879360")
            editor.putString("STATE_TW_ID_abstorm", "489578415377231872")
            editor.putString("STATE_TW_ID_skstorm", "489578619665014784")
            editor.putString("STATE_TW_ID_mbstorm", "489578784731848704")
            editor.putString("STATE_TW_ID_onstorm", "489710428696481795")
            editor.putString("STATE_TW_ID_nbstorm", "489711021922066432")
            editor.putString("STATE_TW_ID_pestorm", "489710770200932352")
            editor.putString("STATE_TW_ID_nsstorm", "489711312742522882")
            editor.putString("STATE_TW_ID_nlwx", "489711657912782848")
            editor.putString("STATE_TW_ID_ntstorm", "489754447413641217")
            editor.putString("STATE_TW_ID_meteoqc", "489754142907170816")
            editor.apply()
        }
        value = preferences.getString("STATE_TW_ID_st", null)
        if (value == null) {
            editor.putString("STATE_TW_ID_st", "611565983380164608")
            editor.apply()
        }
    }

    fun prefInitStateCodeLookup(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("STATE_LOOKUP_District+of+Columbia", null)
        if (value == null) {
            editor.putString("STATE_LOOKUP_Alabama", "AL")
            editor.putString("STATE_LOOKUP_Alaska", "AK")
            editor.putString("STATE_LOOKUP_Arizona", "AZ")
            editor.putString("STATE_LOOKUP_Arkansas", "AR")
            editor.putString("STATE_LOOKUP_California", "CA")
            editor.putString("STATE_LOOKUP_Colorado", "CO")
            editor.putString("STATE_LOOKUP_Connecticut", "CT")
            editor.putString("STATE_LOOKUP_Delaware", "DE")
            editor.putString("STATE_LOOKUP_District+of+Columbia", "DC")
            editor.putString("STATE_LOOKUP_Florida", "FL")
            editor.putString("STATE_LOOKUP_Georgia", "GA")
            editor.putString("STATE_LOOKUP_Hawaii", "HI")
            editor.putString("STATE_LOOKUP_Idaho", "ID")
            editor.putString("STATE_LOOKUP_Illinois", "IL")
            editor.putString("STATE_LOOKUP_Indiana", "IN")
            editor.putString("STATE_LOOKUP_Iowa", "IA")
            editor.putString("STATE_LOOKUP_Kansas", "KS")
            editor.putString("STATE_LOOKUP_Kentucky", "KY")
            editor.putString("STATE_LOOKUP_Louisiana", "LA")
            editor.putString("STATE_LOOKUP_Maine", "ME")
            editor.putString("STATE_LOOKUP_Maryland", "MD")
            editor.putString("STATE_LOOKUP_Massachusetts", "MA")
            editor.putString("STATE_LOOKUP_Michigan", "MI")
            editor.putString("STATE_LOOKUP_Minnesota", "MN")
            editor.putString("STATE_LOOKUP_Mississippi", "MS")
            editor.putString("STATE_LOOKUP_Missouri", "MO")
            editor.putString("STATE_LOOKUP_Montana", "MT")
            editor.putString("STATE_LOOKUP_Nebraska", "NE")
            editor.putString("STATE_LOOKUP_Nevada", "NV")
            editor.putString("STATE_LOOKUP_New+Hampshire", "NH")
            editor.putString("STATE_LOOKUP_New+Jersey", "NJ")
            editor.putString("STATE_LOOKUP_New+Mexico", "NM")
            editor.putString("STATE_LOOKUP_New+York", "NY")
            editor.putString("STATE_LOOKUP_North+Carolina", "NC")
            editor.putString("STATE_LOOKUP_North+Dakota", "ND")
            editor.putString("STATE_LOOKUP_Ohio", "OH")
            editor.putString("STATE_LOOKUP_Oklahoma", "OK")
            editor.putString("STATE_LOOKUP_Oregon", "OR")
            editor.putString("STATE_LOOKUP_Pennsylvania", "PA")
            editor.putString("STATE_LOOKUP_Rhode+Island", "RI")
            editor.putString("STATE_LOOKUP_South+Carolina", "SC")
            editor.putString("STATE_LOOKUP_South+Dakota", "SD")
            editor.putString("STATE_LOOKUP_Tennessee", "TN")
            editor.putString("STATE_LOOKUP_Texas", "TX")
            editor.putString("STATE_LOOKUP_Utah", "UT")
            editor.putString("STATE_LOOKUP_Vermont", "VT")
            editor.putString("STATE_LOOKUP_Virginia", "VA")
            editor.putString("STATE_LOOKUP_Washington", "WA")
            editor.putString("STATE_LOOKUP_West+Virginia", "WV")
            editor.putString("STATE_LOOKUP_Wisconsin", "WI")
            editor.putString("STATE_LOOKUP_Wyoming", "WY")
            editor.apply()
        }
    }

    fun prefInitStateCode(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("STATE_CODE_AL", null)
        if (value == null) {
            editor.putString("STATE_CODE_AL", "MS")
            editor.putString("STATE_CODE_AK", "AK")
            editor.putString("STATE_CODE_AZ", "NM")
            editor.putString("STATE_CODE_AR", "MS")
            editor.putString("STATE_CODE_CA", "NV")
            editor.putString("STATE_CODE_CO", "CO_UT")
            editor.putString("STATE_CODE_CT", "NY")
            editor.putString("STATE_CODE_DE", "VA_WV")
            editor.putString("STATE_CODE_FL", "FL")
            editor.putString("STATE_CODE_GA", "SC")
            editor.putString("STATE_CODE_HI", "HI")
            editor.putString("STATE_CODE_ID", "OR_ID")
            editor.putString("STATE_CODE_IL", "IL_IN")
            editor.putString("STATE_CODE_IN", "IL_IN")
            editor.putString("STATE_CODE_IA", "IL")
            editor.putString("STATE_CODE_KS", "KS")
            editor.putString("STATE_CODE_KY", "IL_IN")
            editor.putString("STATE_CODE_LA", "Gulf_Coast")
            editor.putString("STATE_CODE_ME", "NY")
            editor.putString("STATE_CODE_MD", "VA_WV")
            editor.putString("STATE_CODE_MA", "NY")
            editor.putString("STATE_CODE_MI", "MI")
            editor.putString("STATE_CODE_MN", "SD")
            editor.putString("STATE_CODE_MS", "MS")
            editor.putString("STATE_CODE_MO", "KS")
            editor.putString("STATE_CODE_MT", "MT")
            editor.putString("STATE_CODE_NE", "KS")
            editor.putString("STATE_CODE_NV", "NV")
            editor.putString("STATE_CODE_NH", "NY")
            editor.putString("STATE_CODE_NJ", "NY")
            editor.putString("STATE_CODE_NM", "NM")
            editor.putString("STATE_CODE_NY", "NY")
            editor.putString("STATE_CODE_NC", "SC")
            editor.putString("STATE_CODE_ND", "ND")
            editor.putString("STATE_CODE_OH", "IL_IN")
            editor.putString("STATE_CODE_OK", "TX")
            editor.putString("STATE_CODE_OR", "OR_ID")
            editor.putString("STATE_CODE_PA", "NY")
            editor.putString("STATE_CODE_RI", "NY")
            editor.putString("STATE_CODE_SC", "SC")
            editor.putString("STATE_CODE_SD", "SD")
            editor.putString("STATE_CODE_TN", "IL_IN")
            editor.putString("STATE_CODE_TX", "TX")
            editor.putString("STATE_CODE_UT", "CO_UT")
            editor.putString("STATE_CODE_VT", "NY")
            editor.putString("STATE_CODE_VA", "VA_WV")
            editor.putString("STATE_CODE_WA", "WA_ID")
            editor.putString("STATE_CODE_WV", "VA_WV")
            editor.putString("STATE_CODE_WI", "MI")
            editor.putString("STATE_CODE_WY", "CO_UT")
            editor.apply()
        }
    }

    fun prefInitNWSXY(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("NWS_UNR_X", null)
        if (value == null) {
            editor.putString("NWS_ABC_X", "60.79278")
            editor.putString("NWS_ABC_Y", "-161.87417")
            editor.putString("NWS_ABQ_X", "35.1027")
            editor.putString("NWS_ABQ_Y", "-106.6276")
            editor.putString("NWS_ABR_X", "45.45583")
            editor.putString("NWS_ABR_Y", "-98.41306")
            editor.putString("NWS_ABX_X", "35.14972")
            editor.putString("NWS_ABX_Y", "-106.82333")
            editor.putString("NWS_ACG_X", "56.85278")
            editor.putString("NWS_ACG_Y", "-135.52917")
            editor.putString("NWS_AEC_X", "64.51139")
            editor.putString("NWS_AEC_Y", "-165.295")
            editor.putString("NWS_AFC_X", "61.2060")
            editor.putString("NWS_AFC_Y", "-149.7855")
            editor.putString("NWS_AFG_X", "64.8396")
            editor.putString("NWS_AFG_Y", "-147.7434")
            editor.putString("NWS_AHG_X", "60.725914")
            editor.putString("NWS_AHG_Y", "-151.35146")
            editor.putString("NWS_AIH_X", "59.46194")
            editor.putString("NWS_AIH_Y", "-146.30111")
            editor.putString("NWS_AJK_X", "58.3023")
            editor.putString("NWS_AJK_Y", "-134.4139")
            editor.putString("NWS_AKC_X", "58.67944")
            editor.putString("NWS_AKC_Y", "-156.62944")
            editor.putString("NWS_AKQ_X", "36.98389")
            editor.putString("NWS_AKQ_Y", "-77.0075")
            editor.putString("NWS_ALY_X", "42.6825")
            editor.putString("NWS_ALY_Y", "-73.7899")
            editor.putString("NWS_AMA_X", "35.23333")
            editor.putString("NWS_AMA_Y", "-101.70889")
            editor.putString("NWS_AMX_X", "25.61056")
            editor.putString("NWS_AMX_Y", "-80.41306")
            editor.putString("NWS_APD_X", "65.03556")
            editor.putString("NWS_APD_Y", "-147.49917")
            editor.putString("NWS_APX_X", "44.90722")
            editor.putString("NWS_APX_Y", "-84.71972")
            editor.putString("NWS_ARX_X", "43.82278")
            editor.putString("NWS_ARX_Y", "-91.19111")
            editor.putString("NWS_ATX_X", "48.19472")
            editor.putString("NWS_ATX_Y", "-122.49444")
            editor.putString("NWS_BBX_X", "39.49611")
            editor.putString("NWS_BBX_Y", "-121.63167")
            editor.putString("NWS_BGM_X", "42.19972")
            editor.putString("NWS_BGM_Y", "-75.985")
            editor.putString("NWS_BHX_X", "40.49833")
            editor.putString("NWS_BHX_Y", "-124.29194")
            editor.putString("NWS_BIS_X", "46.77083")
            editor.putString("NWS_BIS_Y", "-100.76028")
            editor.putString("NWS_BLX_X", "45.85389")
            editor.putString("NWS_BLX_Y", "-108.60611")
            editor.putString("NWS_BMX_X", "33.17194")
            editor.putString("NWS_BMX_Y", "-86.76972")
            editor.putString("NWS_BOI_X", "43.5994")
            editor.putString("NWS_BOI_Y", "-116.2645")
            editor.putString("NWS_BOU_X", "40.0107")
            editor.putString("NWS_BOU_Y", "-105.2584")
            editor.putString("NWS_BOX_X", "41.95583")
            editor.putString("NWS_BOX_Y", "-71.1375")
            editor.putString("NWS_BRO_X", "25.91556")
            editor.putString("NWS_BRO_Y", "-97.41861")
            editor.putString("NWS_BTV_X", "44.4686")
            editor.putString("NWS_BTV_Y", "-73.1901")
            editor.putString("NWS_BUF_X", "42.94861")
            editor.putString("NWS_BUF_Y", "-78.73694")
            editor.putString("NWS_BYX_X", "24.59694")
            editor.putString("NWS_BYX_Y", "-81.70333")
            editor.putString("NWS_BYZ_X", "45.7778")
            editor.putString("NWS_BYZ_Y", "-108.5429")
            editor.putString("NWS_CAE_X", "33.94861")
            editor.putString("NWS_CAE_Y", "-81.11861")
            editor.putString("NWS_CAR_X", "46.85897")
            editor.putString("NWS_CAR_Y", "-68.01895")
            editor.putString("NWS_CBW_X", "46.03917")
            editor.putString("NWS_CBW_Y", "-67.80694")
            editor.putString("NWS_CBX_X", "43.49083")
            editor.putString("NWS_CBX_Y", "-116.23444")
            editor.putString("NWS_CCX_X", "40.92306")
            editor.putString("NWS_CCX_Y", "-78.00389")
            editor.putString("NWS_CHS_X", "32.7942")
            editor.putString("NWS_CHS_Y", "-79.9419")
            editor.putString("NWS_CLE_X", "41.41306")
            editor.putString("NWS_CLE_Y", "-81.86")
            editor.putString("NWS_CLX_X", "32.65556")
            editor.putString("NWS_CLX_Y", "-81.04222")
            editor.putString("NWS_CRI_X", "35.2383")
            editor.putString("NWS_CRI_Y", "-97.4602")
            editor.putString("NWS_CRP_X", "27.78389")
            editor.putString("NWS_CRP_Y", "-97.51083")
            editor.putString("NWS_CTP_X", "40.7878")
            editor.putString("NWS_CTP_Y", "-77.8526")
            editor.putString("NWS_CXX_X", "44.51111")
            editor.putString("NWS_CXX_Y", "-73.16639")
            editor.putString("NWS_CYS_X", "41.15194")
            editor.putString("NWS_CYS_Y", "-104.80611")
            editor.putString("NWS_DAX_X", "38.50111")
            editor.putString("NWS_DAX_Y", "-121.67667")
            editor.putString("NWS_DDC_X", "37.76083")
            editor.putString("NWS_DDC_Y", "-99.96833")
            editor.putString("NWS_DFX_X", "29.2725")
            editor.putString("NWS_DFX_Y", "-100.28028")
            editor.putString("NWS_DGX_X", "32.28")
            editor.putString("NWS_DGX_Y", "-89.98444")
            editor.putString("NWS_DIX_X", "39.94694")
            editor.putString("NWS_DIX_Y", "-74.41111")
            editor.putString("NWS_DLH_X", "46.83694")
            editor.putString("NWS_DLH_Y", "-92.20972")
            editor.putString("NWS_DMX_X", "41.73111")
            editor.putString("NWS_DMX_Y", "-93.72278")
            editor.putString("NWS_DOX_X", "38.82556")
            editor.putString("NWS_DOX_Y", "-75.44")
            editor.putString("NWS_DTX_X", "42.69972")
            editor.putString("NWS_DTX_Y", "-83.47167")
            editor.putString("NWS_DVN_X", "41.61167")
            editor.putString("NWS_DVN_Y", "-90.58083")
            editor.putString("NWS_DYX_X", "32.53833")
            editor.putString("NWS_DYX_Y", "-99.25417")
            editor.putString("NWS_EAX_X", "38.81028")
            editor.putString("NWS_EAX_Y", "-94.26417")
            editor.putString("NWS_EKA_X", "40.7852")
            editor.putString("NWS_EKA_Y", "-124.1540")
            editor.putString("NWS_EMX_X", "31.89361")
            editor.putString("NWS_EMX_Y", "-110.63028")
            editor.putString("NWS_ENX_X", "42.58639")
            editor.putString("NWS_ENX_Y", "-74.06444")
            editor.putString("NWS_EOX_X", "31.46028")
            editor.putString("NWS_EOX_Y", "-85.45944")
            editor.putString("NWS_EPZ_X", "31.87306")
            editor.putString("NWS_EPZ_Y", "-106.6975")
            editor.putString("NWS_ESX_X", "35.70111")
            editor.putString("NWS_ESX_Y", "-114.89139")
            editor.putString("NWS_EVX_X", "30.56417")
            editor.putString("NWS_EVX_Y", "-85.92139")
            editor.putString("NWS_EWX_X", "29.70361")
            editor.putString("NWS_EWX_Y", "-98.02806")
            editor.putString("NWS_EYX_X", "35.09778")
            editor.putString("NWS_EYX_Y", "-117.56")
            editor.putString("NWS_FCX_X", "37.02417")
            editor.putString("NWS_FCX_Y", "-80.27417")
            editor.putString("NWS_FDR_X", "34.36222")
            editor.putString("NWS_FDR_Y", "-98.97611")
            editor.putString("NWS_FDX_X", "34.63528")
            editor.putString("NWS_FDX_Y", "-103.62944")
            editor.putString("NWS_FFC_X", "33.36333")
            editor.putString("NWS_FFC_Y", "-84.56583")
            editor.putString("NWS_FGF_X", "47.9069")
            editor.putString("NWS_FGF_Y", "-97.0602")
            editor.putString("NWS_FGZ_X", "35.19502")
            editor.putString("NWS_FGZ_Y", "-111.65310")
            editor.putString("NWS_FSD_X", "43.58778")
            editor.putString("NWS_FSD_Y", "-96.72889")
            editor.putString("NWS_FSX_X", "34.57444")
            editor.putString("NWS_FSX_Y", "-111.19833")
            editor.putString("NWS_FTG_X", "39.78667")
            editor.putString("NWS_FTG_Y", "-104.54528")
            editor.putString("NWS_FWD_X", "32.6963")
            editor.putString("NWS_FWD_Y", "-97.0827")
            editor.putString("NWS_FWS_X", "32.57278")
            editor.putString("NWS_FWS_Y", "-97.30278")
            editor.putString("NWS_GGW_X", "48.20639")
            editor.putString("NWS_GGW_Y", "-106.62417")
            editor.putString("NWS_GID_X", "40.9114")
            editor.putString("NWS_GID_Y", "-98.3601")
            editor.putString("NWS_GJT_X", "39.0836")
            editor.putString("NWS_GJT_Y", "-108.5638")
            editor.putString("NWS_GJX_X", "39.06222")
            editor.putString("NWS_GJX_Y", "-108.21306")
            editor.putString("NWS_GLD_X", "39.36694")
            editor.putString("NWS_GLD_Y", "-101.7")
            editor.putString("NWS_GRB_X", "44.49833")
            editor.putString("NWS_GRB_Y", "-88.11111")
            editor.putString("NWS_GRK_X", "30.72167")
            editor.putString("NWS_GRK_Y", "-97.38278")
            editor.putString("NWS_GRR_X", "42.89389")
            editor.putString("NWS_GRR_Y", "-85.54472")
            editor.putString("NWS_GSP_X", "34.88306")
            editor.putString("NWS_GSP_Y", "-82.22028")
            editor.putString("NWS_GUA_X", "13.45444")
            editor.putString("NWS_GUA_Y", "144.80833")
            editor.putString("NWS_GUM_X", "13.484")
            editor.putString("NWS_GUM_Y", "144.7967")
            editor.putString("NWS_GWX_X", "33.89667")
            editor.putString("NWS_GWX_Y", "-88.32889")
            editor.putString("NWS_GYX_X", "43.89139")
            editor.putString("NWS_GYX_Y", "-70.25694")
            editor.putString("NWS_HDX_X", "33.07639")
            editor.putString("NWS_HDX_Y", "-106.12222")
            editor.putString("NWS_HFO_X", "21.30256")
            editor.putString("NWS_HFO_Y", "-157.84428")
            editor.putString("NWS_HGX_X", "29.47194")
            editor.putString("NWS_HGX_Y", "-95.07889")
            editor.putString("NWS_HKI_X", "21.89417")
            editor.putString("NWS_HKI_Y", "-159.55222")
            editor.putString("NWS_HKM_X", "20.12556")
            editor.putString("NWS_HKM_Y", "-155.77778")
            editor.putString("NWS_HMO_X", "21.13278")
            editor.putString("NWS_HMO_Y", "-157.18")
            editor.putString("NWS_HNX_X", "36.31417")
            editor.putString("NWS_HNX_Y", "-119.63111")
            editor.putString("NWS_HPX_X", "36.73667")
            editor.putString("NWS_HPX_Y", "-87.285")
            editor.putString("NWS_HTX_X", "34.93056")
            editor.putString("NWS_HTX_Y", "-86.08361")
            editor.putString("NWS_HUN_X", "34.6448")
            editor.putString("NWS_HUN_Y", "-86.6672")
            editor.putString("NWS_HWA_X", "19.095")
            editor.putString("NWS_HWA_Y", "-155.56889")
            editor.putString("NWS_ICT_X", "37.65444")
            editor.putString("NWS_ICT_Y", "-97.4425")
            editor.putString("NWS_ICX_X", "37.59083")
            editor.putString("NWS_ICX_Y", "-112.86222")
            editor.putString("NWS_ILM_X", "39.2072")
            editor.putString("NWS_ILM_Y", "-77.8719")
            editor.putString("NWS_ILN_X", "39.42028")
            editor.putString("NWS_ILN_Y", "-83.82167")
            editor.putString("NWS_ILX_X", "40.15056")
            editor.putString("NWS_ILX_Y", "-89.33667")
            editor.putString("NWS_IND_X", "39.7075")
            editor.putString("NWS_IND_Y", "-86.28028")
            editor.putString("NWS_INX_X", "36.175")
            editor.putString("NWS_INX_Y", "-95.56444")
            editor.putString("NWS_IWA_X", "33.28917")
            editor.putString("NWS_IWA_Y", "-111.66917")
            editor.putString("NWS_IWX_X", "41.40861")
            editor.putString("NWS_IWX_Y", "-85.7")
            editor.putString("NWS_JAN_X", "32.3104")
            editor.putString("NWS_JAN_Y", "-90.1890")
            editor.putString("NWS_JAX_X", "30.3453")
            editor.putString("NWS_JAX_X", "30.48444")
            editor.putString("NWS_JAX_Y", "-81.6831")
            editor.putString("NWS_JAX_Y", "-81.70194")
            editor.putString("NWS_JGX_X", "32.675")
            editor.putString("NWS_JGX_Y", "-83.35111")
            editor.putString("NWS_JKL_X", "37.59083")
            editor.putString("NWS_JKL_Y", "-83.31306")
            editor.putString("NWS_JUA_X", "18.1175")
            editor.putString("NWS_JUA_Y", "-66.07861")
            editor.putString("NWS_KEY_X", "24.5627")
            editor.putString("NWS_KEY_Y", "-81.7724")
            editor.putString("NWS_KJK_X", "35.92417")
            editor.putString("NWS_KJK_Y", "126.62222")
            editor.putString("NWS_KSG_X", "36.95972")
            editor.putString("NWS_KSG_Y", "127.01833")
            editor.putString("NWS_LBB_X", "33.65417")
            editor.putString("NWS_LBB_Y", "-101.81361")
            editor.putString("NWS_LBF_X", "41.1431")
            editor.putString("NWS_LBF_Y", "-100.7710")
            editor.putString("NWS_LCH_X", "30.125")
            editor.putString("NWS_LCH_Y", "-93.21583")
            editor.putString("NWS_LGX_X", "47.1158")
            editor.putString("NWS_LGX_Y", "-124.1069")
            editor.putString("NWS_LIX_X", "30.33667")
            editor.putString("NWS_LIX_Y", "-89.82528")
            editor.putString("NWS_LKN_X", "40.8396")
            editor.putString("NWS_LKN_Y", "-115.7587")
            editor.putString("NWS_LMK_X", "38.1722")
            editor.putString("NWS_LMK_Y", "-85.7162")
            editor.putString("NWS_LNX_X", "41.95778")
            editor.putString("NWS_LNX_Y", "-100.57583")
            editor.putString("NWS_LOT_X", "41.60444")
            editor.putString("NWS_LOT_Y", "-88.08472")
            editor.putString("NWS_LOX_X", "33.8228")
            editor.putString("NWS_LOX_Y", "-117.9561")
            editor.putString("NWS_LRX_X", "40.73972")
            editor.putString("NWS_LRX_Y", "-116.80278")
            editor.putString("NWS_LSX_X", "38.69889")
            editor.putString("NWS_LSX_Y", "-90.68278")
            editor.putString("NWS_LTX_X", "33.98917")
            editor.putString("NWS_LTX_Y", "-78.42917")
            editor.putString("NWS_LUB_X", "33.5850")
            editor.putString("NWS_LUB_Y", "-101.8904")
            editor.putString("NWS_LVX_X", "37.97528")
            editor.putString("NWS_LVX_Y", "-85.94389")
            editor.putString("NWS_LWX_X", "38.97628")
            editor.putString("NWS_LWX_Y", "-77.48751")
            editor.putString("NWS_LZK_X", "34.83639")
            editor.putString("NWS_LZK_Y", "-92.26194")
            editor.putString("NWS_MAF_X", "31.94333")
            editor.putString("NWS_MAF_Y", "-102.18889")
            editor.putString("NWS_MAX_X", "42.08111")
            editor.putString("NWS_MAX_Y", "-122.71611")
            editor.putString("NWS_MBX_X", "48.3925")
            editor.putString("NWS_MBX_Y", "-100.86444")
            editor.putString("NWS_MEG_X", "35.1491")
            editor.putString("NWS_MEG_Y", "-90.0151")
            editor.putString("NWS_MFL_X", "25.7744")
            editor.putString("NWS_MFL_Y", "-80.1937")
            editor.putString("NWS_MFR_X", "42.3294")
            editor.putString("NWS_MFR_Y", "-122.8524")
            editor.putString("NWS_MHX_X", "34.77583")
            editor.putString("NWS_MHX_Y", "-76.87639")
            editor.putString("NWS_MKX_X", "42.96778")
            editor.putString("NWS_MKX_Y", "-88.55056")
            editor.putString("NWS_MLB_X", "28.11306")
            editor.putString("NWS_MLB_Y", "-80.65444")
            editor.putString("NWS_MOB_X", "30.67944")
            editor.putString("NWS_MOB_Y", "-88.23972")
            editor.putString("NWS_MPX_X", "44.84889")
            editor.putString("NWS_MPX_Y", "-93.56528")
            editor.putString("NWS_MQT_X", "46.53111")
            editor.putString("NWS_MQT_Y", "-87.54833")
            editor.putString("NWS_MRX_X", "36.16833")
            editor.putString("NWS_MRX_Y", "-83.40194")
            editor.putString("NWS_MSO_X", "46.8685")
            editor.putString("NWS_MSO_Y", "-114.0090")
            editor.putString("NWS_MSX_X", "47.04111")
            editor.putString("NWS_MSX_Y", "-113.98611")
            editor.putString("NWS_MTR_X", "37.7213")
            editor.putString("NWS_MTR_Y", "-122.4369")
            editor.putString("NWS_MTX_X", "41.26278")
            editor.putString("NWS_MTX_Y", "-112.44694")
            editor.putString("NWS_MUX_X", "37.15528")
            editor.putString("NWS_MUX_Y", "-121.8975")
            editor.putString("NWS_MVX_X", "47.52806")
            editor.putString("NWS_MVX_Y", "-97.325")
            editor.putString("NWS_MXX_X", "32.53667")
            editor.putString("NWS_MXX_Y", "-85.78972")
            editor.putString("NWS_NKX_X", "32.91889")
            editor.putString("NWS_NKX_Y", "-117.04194")
            editor.putString("NWS_NQA_X", "35.34472")
            editor.putString("NWS_NQA_Y", "-89.87333")
            editor.putString("NWS_OAX_X", "41.32028")
            editor.putString("NWS_OAX_Y", "-96.36639")
            editor.putString("NWS_ODN_X", "26.30194")
            editor.putString("NWS_ODN_Y", "127.90972")
            editor.putString("NWS_OHX_X", "36.24722")
            editor.putString("NWS_OHX_Y", "-86.5625")
            editor.putString("NWS_OKX_X", "40.86556")
            editor.putString("NWS_OKX_Y", "-72.86444")
            editor.putString("NWS_OTX_X", "47.68056")
            editor.putString("NWS_OTX_Y", "-117.62583")
            editor.putString("NWS_OUN_X", "35.4449")
            editor.putString("NWS_OUN_Y", "-97.5219")
            editor.putString("NWS_PAH_X", "37.06833")
            editor.putString("NWS_PAH_Y", "-88.77194")
            editor.putString("NWS_PBZ_X", "40.53167")
            editor.putString("NWS_PBZ_Y", "-80.21833")
            editor.putString("NWS_PDT_X", "45.69056")
            editor.putString("NWS_PDT_Y", "-118.85278")
            editor.putString("NWS_PHI_X", "39.9754")
            editor.putString("NWS_PHI_Y", "-75.1386")
            editor.putString("NWS_PIH_X", "42.8947")
            editor.putString("NWS_PIH_Y", "-112.4420")
            editor.putString("NWS_PLA_X", "38.73028")
            editor.putString("NWS_PLA_Y", "-27.32167")
            editor.putString("NWS_POE_X", "31.15528")
            editor.putString("NWS_POE_Y", "-92.97583")
            editor.putString("NWS_PQR_X", "45.5031")
            editor.putString("NWS_PQR_Y", "-122.6251")
            editor.putString("NWS_PSR_X", "33.4050")
            editor.putString("NWS_PSR_Y", "-112.0325")
            editor.putString("NWS_PUB_X", "38.2641")
            editor.putString("NWS_PUB_Y", "-104.61483")
            editor.putString("NWS_PUX_X", "38.45944")
            editor.putString("NWS_PUX_Y", "-104.18139")
            editor.putString("NWS_RAH_X", "35.77399")
            editor.putString("NWS_RAH_Y", "-78.64008")
            editor.putString("NWS_RAX_X", "35.66528")
            editor.putString("NWS_RAX_Y", "-78.49")
            editor.putString("NWS_REV_X", "39.5223")
            editor.putString("NWS_REV_Y", "-119.8127")
            editor.putString("NWS_RGX_X", "39.75417")
            editor.putString("NWS_RGX_Y", "-119.46111")
            editor.putString("NWS_RIW_X", "43.06611")
            editor.putString("NWS_RIW_Y", "-108.47667")
            editor.putString("NWS_RLX_X", "38.31194")
            editor.putString("NWS_RLX_Y", "-81.72389")
            editor.putString("NWS_RNK_X", "37.2283")
            editor.putString("NWS_RNK_Y", "-80.4212")
            editor.putString("NWS_RTX_X", "45.715")
            editor.putString("NWS_RTX_Y", "-122.96417")
            editor.putString("NWS_SEW_X", "47.4724")
            editor.putString("NWS_SEW_Y", "-122.3141")
            editor.putString("NWS_SFX_X", "43.10583")
            editor.putString("NWS_SFX_Y", "-112.68528")
            editor.putString("NWS_SGF_X", "37.23528")
            editor.putString("NWS_SGF_Y", "-93.40028")
            editor.putString("NWS_SGX_X", "32.7416")
            editor.putString("NWS_SGX_Y", "-117.1294")
            editor.putString("NWS_SHV_X", "32.45056")
            editor.putString("NWS_SHV_Y", "-93.84111")
            editor.putString("NWS_SJT_X", "31.37111")
            editor.putString("NWS_SJT_Y", "-100.49222")
            editor.putString("NWS_SJU_X", "18.4129")
            editor.putString("NWS_SJU_Y", "-66.0989")
            editor.putString("NWS_SLC_X", "40.7482")
            editor.putString("NWS_SLC_Y", "-111.9155")
            editor.putString("NWS_SOX_X", "33.81778")
            editor.putString("NWS_SOX_Y", "-117.635")
            editor.putString("NWS_SRX_X", "35.29056")
            editor.putString("NWS_SRX_Y", "-94.36167")
            editor.putString("NWS_STO_X", "38.5678")
            editor.putString("NWS_STO_Y", "-121.5007")
            editor.putString("NWS_TAE_X", "30.4293")
            editor.putString("NWS_TAE_Y", "-84.2906")
            editor.putString("NWS_TBW_X", "27.70528")
            editor.putString("NWS_TBW_Y", "-82.40194")
            editor.putString("NWS_TFX_X", "47.45972")
            editor.putString("NWS_TFX_Y", "-111.38444")
            editor.putString("NWS_TLH_X", "30.3975")
            editor.putString("NWS_TLH_Y", "-84.32889")
            editor.putString("NWS_TLX_X", "35.33306")
            editor.putString("NWS_TLX_Y", "-97.2775")
            editor.putString("NWS_TOP_X", "39.0134")
            editor.putString("NWS_TOP_Y", "-95.7071")
            editor.putString("NWS_TSA_X", "36.0961")
            editor.putString("NWS_TSA_Y", "-95.9419")
            editor.putString("NWS_TWC_X", "32.1965")
            editor.putString("NWS_TWC_Y", "-110.9025")
            editor.putString("NWS_TWX_X", "38.99694")
            editor.putString("NWS_TWX_Y", "-96.2325")
            editor.putString("NWS_TYX_X", "43.75583")
            editor.putString("NWS_TYX_Y", "-75.68")
            editor.putString("NWS_UDX_X", "44.125")
            editor.putString("NWS_UDX_Y", "-102.82944")
            editor.putString("NWS_UEX_X", "40.32083")
            editor.putString("NWS_UEX_Y", "-98.44167")
            editor.putString("NWS_UNR_X", "44.0734")
            editor.putString("NWS_UNR_Y", "-103.2259")
            editor.putString("NWS_VAX_X", "30.89")
            editor.putString("NWS_VAX_Y", "-83.00194")
            editor.putString("NWS_VBX_X", "34.83806")
            editor.putString("NWS_VBX_Y", "-120.39583")
            editor.putString("NWS_VEF_X", "36.1273")
            editor.putString("NWS_VEF_Y", "-115.1712")
            editor.putString("NWS_VNX_X", "36.74083")
            editor.putString("NWS_VNX_Y", "-98.1275")
            editor.putString("NWS_VTX_X", "34.41167")
            editor.putString("NWS_VTX_Y", "-119.17861")
            editor.putString("NWS_VWX_X", "38.26")
            editor.putString("NWS_VWX_Y", "-87.7247")
            editor.putString("NWS_YUX_X", "32.49528")
            editor.putString("NWS_YUX_Y", "-114.65583")
            editor.apply()
        }
    }

    fun prefInitRIDXY(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("RID_ABR_Xmay14_2", null)
        if (value == null) {
            editor.putString("RID_ABR_Xmay14_2", "45.451")
            editor.putString("RID_TYX_X", "43.756")
            editor.putString("RID_TYX_Y", "75.68")
            editor.putString("RID_ABR_X", "45.456")
            editor.putString("RID_ABR_Y", "98.413")
            editor.putString("RID_ENX_X", "42.586")
            editor.putString("RID_ENX_Y", "74.064")
            editor.putString("RID_ABX_X", "35.15")
            editor.putString("RID_ABX_Y", "106.824")
            editor.putString("RID_FDR_X", "34.362")
            editor.putString("RID_FDR_Y", "98.977")
            editor.putString("RID_AMA_X", "35.233")
            editor.putString("RID_AMA_Y", "101.709")
            editor.putString("RID_AHG_X", "60.726")
            editor.putString("RID_AHG_Y", "151.351")
            editor.putString("RID_GUA_X", "13.456")
            editor.putString("RID_GUA_Y", "144.811")
            editor.putString("RID_FFC_X", "33.363")
            editor.putString("RID_FFC_Y", "84.566")
            editor.putString("RID_EWX_X", "29.704")
            editor.putString("RID_EWX_Y", "98.029")
            editor.putString("RID_BBX_X", "39.496")
            editor.putString("RID_BBX_Y", "121.632")
            editor.putString("RID_ABC_X", "60.792")
            editor.putString("RID_ABC_Y", "161.876")
            editor.putString("RID_BLX_X", "45.854")
            editor.putString("RID_BLX_Y", "108.607")
            editor.putString("RID_BGM_X", "42.2")
            editor.putString("RID_BGM_Y", "75.985")
            editor.putString("RID_BMX_X", "33.171")
            editor.putString("RID_BMX_Y", "86.77")
            editor.putString("RID_BIS_X", "46.771")
            editor.putString("RID_BIS_Y", "100.76")
            editor.putString("RID_CBX_X", "43.49")
            editor.putString("RID_CBX_Y", "116.236")
            editor.putString("RID_BOX_X", "41.956")
            editor.putString("RID_BOX_Y", "71.137")
            editor.putString("RID_BRO_X", "25.916")
            editor.putString("RID_BRO_Y", "97.419")
            editor.putString("RID_BUF_X", "42.949")
            editor.putString("RID_BUF_Y", "78.737")
            editor.putString("RID_CXX_X", "44.511")
            editor.putString("RID_CXX_Y", "73.166")
            editor.putString("RID_FDX_X", "34.634")
            editor.putString("RID_FDX_Y", "103.619")
            editor.putString("RID_ICX_X", "37.591")
            editor.putString("RID_ICX_Y", "112.862")
            editor.putString("RID_CLX_X", "32.655")
            editor.putString("RID_CLX_Y", "81.042")
            editor.putString("RID_RLX_X", "38.311")
            editor.putString("RID_RLX_Y", "81.723")
            editor.putString("RID_CYS_X", "41.152")
            editor.putString("RID_CYS_Y", "104.806")
            editor.putString("RID_LOT_X", "41.604")
            editor.putString("RID_LOT_Y", "88.085")
            editor.putString("RID_ILN_X", "39.42")
            editor.putString("RID_ILN_Y", "83.822")
            editor.putString("RID_CLE_X", "41.413")
            editor.putString("RID_CLE_Y", "81.86")
            editor.putString("RID_CAE_X", "33.949")
            editor.putString("RID_CAE_Y", "81.119")
            editor.putString("RID_GWX_X", "33.897")
            editor.putString("RID_GWX_Y", "88.329")
            editor.putString("RID_CRP_X", "27.784")
            editor.putString("RID_CRP_Y", "97.511")
            editor.putString("RID_FWS_X", "32.573")
            editor.putString("RID_FWS_Y", "97.303")
            editor.putString("RID_DVN_X", "41.612")
            editor.putString("RID_DVN_Y", "90.581")
            editor.putString("RID_FTG_X", "39.786")
            editor.putString("RID_FTG_Y", "104.546")
            editor.putString("RID_DMX_X", "41.731")
            editor.putString("RID_DMX_Y", "93.723")
            editor.putString("RID_DTX_X", "42.7")
            editor.putString("RID_DTX_Y", "83.472")
            editor.putString("RID_DDC_X", "37.761")
            editor.putString("RID_DDC_Y", "99.969")
            editor.putString("RID_DOX_X", "38.826")
            editor.putString("RID_DOX_Y", "75.44")
            editor.putString("RID_DLH_X", "46.837")
            editor.putString("RID_DLH_Y", "92.21")
            editor.putString("RID_DYX_X", "32.538")
            editor.putString("RID_DYX_Y", "99.254")
            editor.putString("RID_EYX_X", "35.098")
            editor.putString("RID_EYX_Y", "117.561")
            editor.putString("RID_EVX_X", "30.565")
            editor.putString("RID_EVX_Y", "85.922")
            editor.putString("RID_EPZ_X", "31.873")
            editor.putString("RID_EPZ_Y", "106.698")
            editor.putString("RID_LRX_X", "40.74")
            editor.putString("RID_LRX_Y", "116.803")
            editor.putString("RID_BHX_X", "40.499")
            editor.putString("RID_BHX_Y", "124.292")
            editor.putString("RID_APD_X", "65.035")
            editor.putString("RID_APD_Y", "147.501")
            editor.putString("RID_FSX_X", "34.574")
            editor.putString("RID_FSX_Y", "111.198")
            editor.putString("RID_HPX_X", "36.737")
            editor.putString("RID_HPX_Y", "87.285")
            editor.putString("RID_GRK_X", "30.722")
            editor.putString("RID_GRK_Y", "97.383")
            editor.putString("RID_POE_X", "31.155")
            editor.putString("RID_POE_Y", "92.976")
            editor.putString("RID_EOX_X", "31.46")
            editor.putString("RID_EOX_Y", "85.459")
            editor.putString("RID_SRX_X", "35.29")
            editor.putString("RID_SRX_Y", "94.362")
            editor.putString("RID_IWX_X", "41.359")
            editor.putString("RID_IWX_Y", "85.7")
            editor.putString("RID_APX_X", "44.906")
            editor.putString("RID_APX_Y", "84.72")
            editor.putString("RID_GGW_X", "48.206")
            editor.putString("RID_GGW_Y", "106.625")
            editor.putString("RID_GLD_X", "39.367")
            editor.putString("RID_GLD_Y", "101.7")
            editor.putString("RID_MVX_X", "47.528")
            editor.putString("RID_MVX_Y", "97.325")
            editor.putString("RID_GJX_X", "39.062")
            editor.putString("RID_GJX_Y", "108.214")
            editor.putString("RID_GRR_X", "42.894")
            editor.putString("RID_GRR_Y", "85.545")
            editor.putString("RID_TFX_X", "47.46")
            editor.putString("RID_TFX_Y", "111.385")
            editor.putString("RID_GRB_X", "44.499")
            editor.putString("RID_GRB_Y", "88.111")
            editor.putString("RID_GSP_X", "34.883") // "34.879"
            editor.putString("RID_GSP_Y", "82.22") // "82.216"
            editor.putString("RID_UEX_X", "40.321")
            editor.putString("RID_UEX_Y", "98.442")
            editor.putString("RID_HDX_X", "33.077")
            editor.putString("RID_HDX_Y", "106.12")
            editor.putString("RID_CBW_X", "46.039")
            editor.putString("RID_CBW_Y", "67.806")
            editor.putString("RID_HGX_X", "29.472")
            editor.putString("RID_HGX_Y", "95.079")
            editor.putString("RID_HTX_X", "34.931")
            editor.putString("RID_HTX_Y", "86.084")
            editor.putString("RID_IND_X", "39.708")
            editor.putString("RID_IND_Y", "86.28")
            editor.putString("RID_JKL_X", "37.591")
            editor.putString("RID_JKL_Y", "83.313")
            editor.putString("RID_JAX_X", "30.485")
            editor.putString("RID_JAX_Y", "81.702")
            editor.putString("RID_EAX_X", "38.81")
            editor.putString("RID_EAX_Y", "94.264")
            editor.putString("RID_BYX_X", "24.597")
            editor.putString("RID_BYX_Y", "81.703")
            editor.putString("RID_AKC_X", "58.68")
            editor.putString("RID_AKC_Y", "156.627")
            editor.putString("RID_MRX_X", "36.168")
            editor.putString("RID_MRX_Y", "83.402")
            editor.putString("RID_ARX_X", "43.823")
            editor.putString("RID_ARX_Y", "91.191")
            editor.putString("RID_LCH_X", "30.125")
            editor.putString("RID_LCH_Y", "93.216")
            editor.putString("RID_ESX_X", "35.701")
            editor.putString("RID_ESX_Y", "114.891")
            editor.putString("RID_DFX_X", "29.273")
            editor.putString("RID_DFX_Y", "100.28")
            editor.putString("RID_ILX_X", "40.15")
            editor.putString("RID_ILX_Y", "89.337")
            editor.putString("RID_LZK_X", "34.836")
            editor.putString("RID_LZK_Y", "92.262")
            editor.putString("RID_VTX_X", "34.412")
            editor.putString("RID_VTX_Y", "119.179")
            editor.putString("RID_LVX_X", "37.975")
            editor.putString("RID_LVX_Y", "85.944")
            editor.putString("RID_LBB_X", "33.654")
            editor.putString("RID_LBB_Y", "101.814")
            editor.putString("RID_MQT_X", "46.531") // 46.31
            editor.putString("RID_MQT_Y", "87.548") // 87.32
            editor.putString("RID_MXX_X", "32.537")
            editor.putString("RID_MXX_Y", "85.79")
            editor.putString("RID_MAX_X", "42.081")
            editor.putString("RID_MAX_Y", "122.717")
            editor.putString("RID_MLB_X", "28.113")
            editor.putString("RID_MLB_Y", "80.654")
            editor.putString("RID_NQA_X", "35.345")
            editor.putString("RID_NQA_Y", "89.873")
            editor.putString("RID_AMX_X", "25.611")
            editor.putString("RID_AMX_Y", "80.413")
            editor.putString("RID_AIH_X", "59.46")
            editor.putString("RID_AIH_Y", "146.303")
            editor.putString("RID_MAF_X", "31.943")
            editor.putString("RID_MAF_Y", "102.189")
            editor.putString("RID_MKX_X", "42.968")
            editor.putString("RID_MKX_Y", "88.551")
            editor.putString("RID_MPX_X", "44.849") // was .845
            editor.putString("RID_MPX_Y", "93.565") // was .560
            editor.putString("RID_MBX_X", "48.393")
            editor.putString("RID_MBX_Y", "100.864")
            editor.putString("RID_MSX_X", "47.041")
            editor.putString("RID_MSX_Y", "113.986")
            editor.putString("RID_MOB_X", "30.679")
            editor.putString("RID_MOB_Y", "88.24")
            editor.putString("RID_HMO_X", "21.133")
            editor.putString("RID_HMO_Y", "157.18")
            editor.putString("RID_VAX_X", "30.89")
            editor.putString("RID_VAX_Y", "83.002")
            editor.putString("RID_MHX_X", "34.776")
            editor.putString("RID_MHX_Y", "76.876")
            editor.putString("RID_OHX_X", "36.247")
            editor.putString("RID_OHX_Y", "86.563")
            editor.putString("RID_LIX_X", "30.337")
            editor.putString("RID_LIX_Y", "89.825")
            editor.putString("RID_OKX_X", "40.865")
            editor.putString("RID_OKX_Y", "72.864")
            editor.putString("RID_AEC_X", "64.512")
            editor.putString("RID_AEC_Y", "165.293")
            editor.putString("RID_AKQ_X", "36.984")
            editor.putString("RID_AKQ_Y", "77.008")
            editor.putString("RID_LNX_X", "41.958")
            editor.putString("RID_LNX_Y", "100.576")
            editor.putString("RID_TLX_X", "35.333")
            editor.putString("RID_TLX_Y", "97.278")
            editor.putString("RID_OAX_X", "41.32")
            editor.putString("RID_OAX_Y", "96.367")
            editor.putString("RID_PAH_X", "37.068")
            editor.putString("RID_PAH_Y", "88.772")
            editor.putString("RID_PDT_X", "45.691")
            editor.putString("RID_PDT_Y", "118.853")
            editor.putString("RID_DIX_X", "39.947")
            editor.putString("RID_DIX_Y", "74.411")
            editor.putString("RID_IWA_X", "33.289")
            editor.putString("RID_IWA_Y", "111.67")
            editor.putString("RID_PBZ_X", "40.532")
            editor.putString("RID_PBZ_Y", "80.218")
            editor.putString("RID_SFX_X", "43.106")
            editor.putString("RID_SFX_Y", "112.686")
            editor.putString("RID_GYX_X", "43.891")
            editor.putString("RID_GYX_Y", "70.256")
            editor.putString("RID_RTX_X", "45.715")
            editor.putString("RID_RTX_Y", "122.965")
            editor.putString("RID_PUX_X", "38.46")
            editor.putString("RID_PUX_Y", "104.181")
            editor.putString("RID_RAX_X", "35.665")
            editor.putString("RID_RAX_Y", "78.49")
            editor.putString("RID_UDX_X", "44.125")
            editor.putString("RID_UDX_Y", "102.83")
            editor.putString("RID_RGX_X", "39.754")
            editor.putString("RID_RGX_Y", "119.462")
            editor.putString("RID_RIW_X", "43.066")
            editor.putString("RID_RIW_Y", "108.477")
            editor.putString("RID_FCX_X", "37.024")
            editor.putString("RID_FCX_Y", "80.274")
            editor.putString("RID_JGX_X", "32.675")
            editor.putString("RID_JGX_Y", "83.351")
            editor.putString("RID_DAX_X", "38.501")
            editor.putString("RID_DAX_Y", "121.678")
            editor.putString("RID_LSX_X", "38.699")
            editor.putString("RID_LSX_Y", "90.683")
            editor.putString("RID_MTX_X", "41.263")
            editor.putString("RID_MTX_Y", "112.448")
            editor.putString("RID_SJT_X", "31.371")
            editor.putString("RID_SJT_Y", "100.492")
            editor.putString("RID_NKX_X", "32.919")
            editor.putString("RID_NKX_Y", "117.041")
            editor.putString("RID_MUX_X", "37.155")
            editor.putString("RID_MUX_Y", "121.898")
            editor.putString("RID_HNX_X", "36.314")
            editor.putString("RID_HNX_Y", "119.632")
            editor.putString("RID_JUA_X", "18.116")
            editor.putString("RID_JUA_Y", "66.078")
            editor.putString("RID_SOX_X", "33.818")
            editor.putString("RID_SOX_Y", "117.636")
            editor.putString("RID_ATX_X", "48.195")
            editor.putString("RID_ATX_Y", "122.496")
            editor.putString("RID_SHV_X", "32.451")
            editor.putString("RID_SHV_Y", "93.841")
            editor.putString("RID_FSD_X", "43.588")
            editor.putString("RID_FSD_Y", "96.729")
            editor.putString("RID_ACG_X", "56.853")
            editor.putString("RID_ACG_Y", "135.528")
            editor.putString("RID_HKI_X", "21.894")
            editor.putString("RID_HKI_Y", "159.552")
            editor.putString("RID_HWA_X", "19.095")
            editor.putString("RID_HWA_Y", "155.569")
            editor.putString("RID_OTX_X", "47.681")
            editor.putString("RID_OTX_Y", "117.626")
            editor.putString("RID_SGF_X", "37.235")
            editor.putString("RID_SGF_Y", "93.4")
            editor.putString("RID_CCX_X", "40.923")
            editor.putString("RID_CCX_Y", "78.004")
            editor.putString("RID_LWX_X", "38.976")
            editor.putString("RID_LWX_Y", "77.487")
            editor.putString("RID_TLH_X", "30.398") // orig 30.2351
            editor.putString("RID_TLH_Y", "84.329") // orig 84.1944
            editor.putString("RID_TBW_X", "27.705")
            editor.putString("RID_TBW_Y", "82.402")
            editor.putString("RID_TWX_X", "38.997")
            editor.putString("RID_TWX_Y", "96.232")
            editor.putString("RID_EMX_X", "31.894")
            editor.putString("RID_EMX_Y", "110.63")
            editor.putString("RID_INX_X", "36.175") // "36.171"
            editor.putString("RID_INX_Y", "95.564") // "95.560"
            editor.putString("RID_VNX_X", "36.741")
            editor.putString("RID_VNX_Y", "98.128")
            editor.putString("RID_VBX_X", "34.839")
            editor.putString("RID_VBX_Y", "120.398")
            editor.putString("RID_ICT_X", "37.654")
            editor.putString("RID_ICT_Y", "97.443")
            editor.putString("RID_LTX_X", "33.989")
            editor.putString("RID_LTX_Y", "78.429")
            editor.putString("RID_YUX_X", "32.495")
            editor.putString("RID_YUX_Y", "114.656")
            editor.putString("RID_LGX_X", "47.116")
            editor.putString("RID_LGX_Y", "124.107")
            editor.putString("RID_DGX_X", "32.28")
            editor.putString("RID_DGX_Y", "89.984")
            editor.putString("RID_VWX_X", "38.26")
            editor.putString("RID_VWX_Y", "87.724")
            editor.putString("RID_HKM_X", "20.125")
            editor.putString("RID_HKM_Y", "155.778")
            editor.apply()
        }
    }


    fun prefInitRIDXY2(context: Context) {
        val preferences = PreferenceManager.getDefaultSharedPreferences(context)
        val editor = preferences.edit()
        val value = preferences.getString("RID_TATL_Y", null)
        if (value == null) {
            editor.putString("RID_aug12_4_X", "aug112014") // nws conus
            editor.putString("RID_latest_X", "36.105") // nws conus
            editor.putString("RID_latest_Y", "97.141")
            editor.putString("RID_centgrtlakes_X", "42.127")
            editor.putString("RID_centgrtlakes_Y", "84.544")
            editor.putString("RID_uppermissvly_X", "42.75")
            editor.putString("RID_uppermissvly_Y", "97.10")
            editor.putString("RID_northrockies_X", "42.75")
            editor.putString("RID_northrockies_Y", "108.60")
            editor.putString("RID_northeast_X", "42.425")
            editor.putString("RID_northeast_Y", "74.10")
            editor.putString("RID_pacnorthwest_X", "42.425")
            editor.putString("RID_pacnorthwest_Y", "120.10")
            editor.putString("RID_pacsouthwest_X", "35.15")
            editor.putString("RID_pacsouthwest_Y", "120.15")
            editor.putString("RID_southrockies_X", "32.5")
            editor.putString("RID_southrockies_Y", "110.50")
            editor.putString("RID_southplains_X", "31.6")
            editor.putString("RID_southplains_Y", "100.00")
            editor.putString("RID_southmissvly_X", "31.6")
            editor.putString("RID_southmissvly_Y", "90.00")
            editor.putString("RID_southeast_X", "29.86")
            editor.putString("RID_southeast_Y", "82.658")
            editor.putString("RID_hawaii_X", "19.91")
            editor.putString("RID_hawaii_Y", "157.55")
            editor.putString("RID_iowa_conus_mosaic_X", "37.00")
            editor.putString("RID_iowa_conus_mosaic_Y", "96.00")
            editor.putString("RID_iowa_mosaic_USCOMP_X", "37.00")
            editor.putString("RID_iowa_mosaic_USCOMP_Y", "96.00")
            editor.putString("RID_iowa_mosaic_AKCOMP_X", "60.77")  // original scale factor is 100
            editor.putString("RID_iowa_mosaic_AKCOMP_Y", "150.36")
            editor.putString("RID_iowa_mosaic_HICOMP_X", "19.928")  // original scale factor is 200
            editor.putString("RID_iowa_mosaic_HICOMP_Y", "156.94")
            editor.putString("RID_iowa_mosaic_PRCOMP_X", "18.205")
            editor.putString("RID_iowa_mosaic_PRCOMP_Y", "66.158")
            editor.putString("RID_TDTW_X", "42.11111")  // Detroit (DTW), MI TDTW DTX 772
            editor.putString("RID_TDTW_Y", "83.515")
            editor.putString("RID_TADW_X", "5") //  Andrews Air Force Base (ADW), MD TADW LWX 346
            editor.putString("RID_TADW_Y", "5")
            editor.putString("RID_TATL_X", "33.646193") // Atlanta (ATL), GA TATL FFC 1,075
            editor.putString("RID_TATL_Y", "84.262233")
            editor.putString("RID_TBNA_X", "35.979079") // Nashville (BNA), TN TBNA OHX 817
            editor.putString("RID_TBNA_Y", "86.661691")
            editor.putString("RID_TBOS_X", "42.15806") // Boston (BOS), MA TBOS BOX 264
            editor.putString("RID_TBOS_Y", "70.93389")
            editor.putString("RID_TBWI_X", "39.09056") // Baltimore/Wash (BWI), MD TBWI LWX 342
            editor.putString("RID_TBWI_Y", "76.63")
            editor.putString("RID_TLVE_X", "41.289372") // Cleveland (CLE), OH TLVE CLE 931
            editor.putString("RID_TLVE_Y", "82.007419")
            editor.putString("RID_TCLT_X", "35.337269") // Charlotte (CLT), NC TCLT GSP 871
            editor.putString("RID_TCLT_Y", "80.885006")
            editor.putString("RID_TCMH_X", "40.00611") // Columbus (CMH), OH TCMH ILN 1,148
            editor.putString("RID_TCMH_Y", "82.71556")
            editor.putString("RID_TCVG_X", "38.89778") // Covington (CVG), OH TCVG ILN 1,053
            editor.putString("RID_TCVG_Y", "84.58028")
            editor.putString("RID_TDAL_X", "32.92494") // Dallas Love Field (DAL), TX TDAL FWD 622
            editor.putString("RID_TDAL_Y", "96.968473")
            editor.putString("RID_TDAY_X", "40.021376") // Dayton (DAY), OH TDAY ILN 1,019
            editor.putString("RID_TDAY_Y", "84.123077")
            editor.putString("RID_TDCA_X", "38.758853") // Washington National (DCA), MD TDCA LWX 345
            editor.putString("RID_TDCA_Y", "76.961837")
            editor.putString("RID_TDEN_X", "39.72722") // Denver (DEN), CO TDEN BOU 5,701
            editor.putString("RID_TDEN_Y", "104.52639")
            editor.putString("RID_TDFW_X", "33.064286") // Dallas/Ft. Worth (DFW), TX TDFW FWD 585
            editor.putString("RID_TDFW_Y", "96.915554")
            editor.putString("RID_TEWR_X", "40.593397") // Newark (EWR), NJ TEWR OKX 136
            editor.putString("RID_TEWR_Y", "74.270164")
            editor.putString("RID_TFLL_X", "26.142601") // Fort Lauderdale (FLL), FL TFLL MFL 120
            editor.putString("RID_TFLL_Y", "80.34382")
            editor.putString("RID_THOU_X", "29.515852") // Houston Hobby (HOU), TX THOU HGX 116
            editor.putString("RID_THOU_Y", "95.241692")
            editor.putString("RID_TIAD_X", "39.083667") // Dulles (IAD), VA TIAD LWX 473
            editor.putString("RID_TIAD_Y", "77.529224")
            editor.putString("RID_TIAH_X", "30.06472") // Houston International (IAH), TX TIAH HGX 253
            editor.putString("RID_TIAH_Y", "95.5675")
            editor.putString("RID_TICT_X", "37.506844") // Wichita (ICT), KS TICH ICT 1,350
            editor.putString("RID_TICT_Y", "97.437228")
            editor.putString("RID_TIDS_X", "39.636556") // Indianapolis (IND), IN TIDS IND 847
            editor.putString("RID_TIDS_Y", "86.435286")
            editor.putString("RID_TJFK_X", "40.588633") // New York City (JFK), NY TJFK OKX 112
            editor.putString("RID_TJFK_Y", "73.880303") // NY	FLOYD BENNETT FIELD	40.588633, -73.880303	5647
            editor.putString("RID_TLAS_X", "36.144") // Las Vegas (LAS), NV TLAS VEF 2,058
            editor.putString("RID_TLAS_Y", "115.007")
            editor.putString("RID_TMCI_X", "39.49861") // Kansas City (MCI), MO TMCI EAX 1,090
            editor.putString("RID_TMCI_Y", "94.74167")
            editor.putString("RID_TMCO_X", "28.343125") // Orlando International (MCO), FL TMCO MLB 169
            editor.putString("RID_TMCO_Y", "81.324674")
            editor.putString("RID_TMDW_X", "41.6514") // Chicago Midway (MDW), IL TMDW LOT 763
            editor.putString("RID_TMDW_Y", "87.7294")
            editor.putString("RID_TMEM_X", "34.896044") // Memphis (MEM), TN TMEM MEG 483
            editor.putString("RID_TMEM_Y", "89.992727")
            editor.putString("RID_TMIA_X", "25.757083") // Miami (MIA), FL TMIA MFL 125
            editor.putString("RID_TMIA_Y", "80.491076")
            editor.putString("RID_TMKE_X", "42.81944") // Milwaukee (MKE), WI TMKE MKX 933
            editor.putString("RID_TMKE_Y", "88.04611")
            editor.putString("RID_TMSP_X", "44.870902") // Minneapolis (MSP), MN TMSP MPX 1,120
            editor.putString("RID_TMSP_Y", "92.932257")
            editor.putString("RID_TMSY_X", "30.021389") // New Orleans (MSY), LA TMSY LIX 99
            editor.putString("RID_TMSY_Y", "90.402919")
            editor.putString("RID_TOKC_X", "35.27611") // Oklahoma City (OKC), OK TOKC OUN 1,308
            editor.putString("RID_TOKC_Y", "97.51")
            editor.putString("RID_TORD_X", "41.796589") // Chicago O'Hare (ORD), IL TORD LOT 744
            editor.putString("RID_TORD_Y", "87.857628")
            editor.putString("RID_TPBI_X", "26.687812") // West Palm Beach (PBI), FL TPBI MFL 133
            editor.putString("RID_TPBI_Y", "80.272931")
            editor.putString("RID_TPHL_X", "39.950061") // Philadelphia (PHL), PA TPHL PHI 153
            editor.putString("RID_TPHL_Y", "75.069979")
            editor.putString("RID_TPHX_X", "33.420352") // Phoenix (PHX), AZ TPHX PSR 1,089
            editor.putString("RID_TPHX_Y", "112.16318")
            editor.putString("RID_TPIT_X", "40.501066") // Pittsburgh (PIT), PA TPIT PBZ 1,386
            editor.putString("RID_TPIT_Y", "80.486586")
            editor.putString("RID_TRDU_X", "36.001401") // Raleigh Durham (RDU), NC TRDU RAH 515
            editor.putString("RID_TRDU_Y", "78.697942")
            editor.putString("RID_TSDF_X", "38.04581") // Louisville (SDF), KY TSDF LMK 731
            editor.putString("RID_TSDF_Y", "85.610641")
            editor.putString("RID_TSJU_X", "18.47394") // San Juan (SJU), PR TSJU SJU 157
            editor.putString("RID_TSJU_Y", "66.17891")
            editor.putString("RID_TSLC_X", "40.967222") // Salt Lake City (SLC), UT TSLC SLC 4,295
            editor.putString("RID_TSLC_Y", "111.929722")
            editor.putString("RID_TSTL_X", "38.804691") // St Louis (STL), MO TSTL LSX 647
            editor.putString("RID_TSTL_Y", "90.488558")
            editor.putString("RID_TTPA_X", "27.85867") // Tampa Bay (TPA), FL TTPA TBW 93
            editor.putString("RID_TTPA_Y", "82.51755")
            editor.putString("RID_TTUL_X", "36.070184") // Tulsa (TUL), OK TTUL TSA 823
            editor.putString("RID_TTUL_Y", "95.826313")
            editor.apply()
        }
    }
}



