//modded by ELY M.
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url = 'https://maven.google.com' }
    }

    dependencies {
    }
}

plugins {
    id 'com.android.application' version '9.4.1' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}



